version: '3.8'

services:
  django:
      container_name: django-webserver
      build: .
      command: ["sh", "./run_server.sh"]
      volumes:
        - static_volume:/app/static
      expose:
        - "8000"
      # environment:
      #   - PRODUCTION_HOST=*
      #   - SECRET_KEY=9dvw5lrq60i!0t11-=()5oljq6-cwb1gqsg47yk@z6qdgjri)m
      #   - DB_NAME=dj-jrd
      #   - DB_USER=dj-postgres
      #   - DB_PASSWORD=Pa$$w0rd
      #   - DB_HOST=postgres
      #   - DB_PORT=5432
      env_file:
        - .env
      restart: always
      depends_on:
        - postgres
      networks:
        - dj

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: dj-jrd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dj

  nginx:
    build: ./nginx
    container_name: nginx-webserver
    ports:
      - "80:80"
    restart: always
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - django
    networks:
      - dj

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PGadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@junraider.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dj

volumes:
  postgres_data:
  static_volume:
  pgadmin_data:
networks:
  dj:
