version: '3.8'

services:
  django:
      container_name: django-webserver
      build: .
      command: poetry run gunicorn project_jrd.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/app/static
      expose:
        - "8000"   # Map port 80 of host to port 80 of container
      environment:
        - DJANGO_ENV=production
        - PRODUCTION_HOST=192.168.10.10
        - SECRET_KEY=9dvw5lrq60i!0t11-=()5oljq6-cwb1gqsg47yk@z6qdgjri)m
        - DB_NAME=dj-jrd
        - DB_USER=postgres
        - DB_PASSWORD=Pa$$w0rd
        - DB_HOST=localhost
        - DB_PORT=5432
      restart: always
      depends_on:
        - postgres
      networks:
        - dj

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: dj-jrd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa$$w0rd
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dj

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - django
    networks:
      - dj

volumes:
  postgres_data:
  static_volume:
networks:
  dj: