# Secret for PGAdmin credentials
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  # Base64 encoded values
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=  # 'admin@example.com' encoded
  PGADMIN_DEFAULT_PASSWORD: cGdhZG1pbjEyMzQ=  # 'pgadmin1234' encoded

---
# PGAdmin Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: pgadmin-secret
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-data-pvc

---
# PGAdmin Service
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
  - port: 5050
    targetPort: 80
  type: ClusterIP  # Change to LoadBalancer or use Ingress if needed

---
# PersistentVolumeClaim for PGAdmin data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed