name: CI/CD for Django App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: dj-jrd
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Wait for PostgreSQL to be ready
        run: sleep 20s

      - name: Run Django tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_NAME: dj-jrd
          DB_USER: postgres
          DB_PASSWORD: password
        run: |
          poetry run python manage.py migrate
          poetry run python manage.py test